### DISCUSSION TITLE
请问iOS中，中英切换的英文键盘的修改

### DISCUSSION THREAD

**Discussion by ZmdnaHF0ZmFqYXZ0O** [KyleBing/rime-wubi86-jidian#152] [Q&A] [answered]
使用仓输入法，导入wubi86-jidian后，中英切换后的英文键盘只带有很少的符号输入，如果想要修改此键盘的按键上滑可输出的字符，应该修改哪个文件？谢谢！

**Comment by KyleBing** [comment, marked as answer]
需要自定义键盘文件，与词库无关。
自定义键盘文件说明：https://github.com/imfuxiao/Hamster/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B8%83%E5%B1%80
键盘文件定义工具：https://lost-melody.github.io/hamster-tools/

**Reply by ZmdnaHF0ZmFqYXZ0O** [reply]
感谢你的回复！请问我使用自定义工具完成自定义后，是需要在hamster.yaml 中的：
```
keyboards:
  __include: 

```
添加自定义的键盘文件名，还是在wubi86_jidian.schema.yaml中添加？

**Reply by ZmdnaHF0ZmFqYXZ0O** [reply]
我已经从自定义工具页面找到答案了，谢谢！

#應用到倉APP
通過内置導入功能導入
將從此頁面導出的完整配置文件移動到 iPhone/Hamster/ 下
在倉輸入法「自定義鍵盤」右上角加號菜單中選擇「導入配色與佈局」, 並選擇剛才準備的文件
通過文件手動導入
將從此頁面導出的完整配置文件存儲爲 Rime/custom_configs.yaml
新建文件 Rime/hamster.custom.yaml, 並填入以下内容:
```
patch:
  # 倸用此方法導入配置, 請確認已經在倉APP中「重置界面設置」
  # 如果使用過倉内置編輯器的編輯或導入功能, 則此處配置會被覆盖
  keyboard/colorSchemas:
    # 導入配色方案
    __include: custom_configs:/keyboard/colorSchemas
  keyboards:
    # 導入鍵盤佈局
    __include: custom_configs:/keyboards
```
