### DISCUSSION TITLE
请教 四码上屏、句号上屏

### DISCUSSION THREAD

**Discussion by gclintj** [KyleBing/rime-wubi86-jidian#64] [Q&A] [answered]
```
# wubi86_jidian.schema.yaml

speller:
  max_code_length: 4                    # 四码上屏
  auto_select: true                     # 自动上屏
```

四码上屏的功能是原本就有，你只是添加了这一行配置，还是你自己开发加入的功能？
自动上屏 是怎样的一个功能？

另想请教一下， [句号上屏](https://github.com/rime/home/issues/823)  可以实现吗？是如何配置的？

Edit:
Solution:
原来我最初的主要问题是，应该把配置文件放在Rime下而非build下，以及配置文件开头要加 `patch:` .
四码上屏用开关在speller加配置语句。
句号上屏key_binder内取消了句号用于翻页的binding 似乎就足够了。

**Comment by KyleBing** [comment]
四码上屏功能本来就有，只是需要把配置写出来。
句号应该也可以，需要研究一下。目前是可以通过标点直接顶字上屏的，不过会留下标点符号。

**Reply by gclintj** [reply]
哦，方便指出一下是在哪里找到四码上屏的吗？我觉得我也过了一遍Rime的文档了，但没找到这个功能。
想看看相关页面多学习了解一下。

对，就是想留下标点符号。Rime默认就支持 , ! ? 但不支持句号。

**Comment by KyleBing** [comment, marked as answer]
支持句号上屏呀  `default.custom.yaml` 中的标点定义中，带有 `commit` 的都是可以作为上屏标点用的，直接上屏第一位置的内容，并留下标点。
四码上屏只是定义的输入码的长度，四码就是 4 嘛。

目前句号上屏是能正常使用的。

**Reply by gclintj** [reply]
Rime默认句号是向后翻页的。我把翻页的功能去掉了，还是无法用句号上屏。
四码上屏我加了你那行配置，还是没有变化。

有什么调试的建议吗？

**Reply by KyleBing** [reply]
查看 `default.custom.yaml` 文件 `key_binder` 那一块，定义一下上下翻页的按键应该就可以了。
可以参考

```yaml
  key_binder:
    bindings:
      #     - {accept: comma, send: 2, when: has_menu}  # 候选2 用逗号选择 （修改的时候不要多加或少加空格，跟前面的对齐就好了）
      #     - {accept: period, send: 3, when: has_menu} # 候选3 用句号选择
      - {accept: semicolon, send: 2, when: has_menu}  # 候选2 用分号
      - {accept: apostrophe, send: 3, when: has_menu} # 候选3 用单引号
      # 上下翻页 [ ]
      - {accept: bracketleft, send: Page_Up, when: paging}
      - {accept: bracketright, send: Page_Down, when: has_menu}
      # 上下翻页 - =
      - {accept: minus, send: Page_Up, when: paging}
      - {accept: equal, send: Page_Down, when: has_menu}
#      - {accept: Return, send: Escape, when: composing}   # 回车清码
```
