### ISSUE TITLE
macOS 下如何设置隐藏候选窗口及单字出简不出全

### ISSUE THREAD

**Issue by tiange1949** [KyleBing/rime-wubi86-jidian#109]
KyleBing大神，你好，作为一个常年单字选手，请问macOS下能实现隐藏候选窗口的功能吗？
另外，为了实现彻底盲打，想问一下大神，可以在单字输入的基础上再加一个出简不出全的功能吗？
这样，重码率基本为0，从此汉字和编码基本一一对应，简直太爽 了。

**Comment by tiange1949** [comment]
问题已解决，步骤如下：

1. 将`wubi86_jidian.dict.yaml`文件的极点五笔码表替换为出简不出全的QQ五笔码表，这样6761个常用汉字的重码汉字只有285个；
2. 打开`wubi86_jidian.schema.yaml`文件，定位到以下代码，设置为纯单字，取消四码上屏和四码唯一直接上屏
```yaml
filters:
#    - simplifier@tradition
#    - lua_filter@single_char_first_filter # 单字优先
     - lua_filter@single_char_only # 纯单字
speller:
#  max_code_length: 4                    # 四码上屏
#  auto_select: false                    # 四码唯一时，自动上屏
#  auto_clear: max_length                # 空码时自动清空
```
3. 将候选文字颜色改为和候选框背景颜色一样

经过以上设置后，基本可以实现不看候选框打字，实现真正的**“盲打”**。
