### ISSUE TITLE
通过z键输入重复内容。

### ISSUE THREAD

**Issue by redleafnew** [KyleBing/rime-wubi86-jidian#118]
小狼毫有没有办法快速输入上次输入的内容。如刚输入了恭喜，按某个键，快速再输入恭喜，在极点中是 z键。

估计是用到`history_translator`，这个怎么配置？
搜索到了https://codeleading.com/article/56862155758/
https://github.com/LEOYoon-Tsaw/Rime_collections/blob/3fd93695df833145d394e3b1b18153cc76735610/Rime_description.md#%E4%B8%89translators

**Comment by redleafnew** [comment]
https://github.com/rime/home/issues/396 按这个解决了。

供大家参考。

```
patch:
  engine:
    translators:
      - history_translator@history      #历史输入，按z输入刚才输入的内容

  # 历史输入，按z输入刚才输入的内容
  history:  
    input: z
    size: 1
```
