### ISSUE TITLE
有什么思路实现带前缀的混输方案？

### ISSUE THREAD

**Issue by plutotree** [KyleBing/rime-wubi86-jidian#138]
第一点是和拼音的混输
现在有五笔拼音的混输方案，但是这样重码率太高，不利于盲打。想要的是可以使用前缀比如z来实现拼音的输入，但是想要的并不是反查模式，反查只有完整输入才能出结果。
比如我输入zzhr 就可以提示中华人民 中华人民共和国，在反查模式下是需要输入完整才能提示

第二点是英文的混输 现在对于中英文混杂的内容需要频繁来回切换中英文模式很不方便，另一点也希望能有联想输入。所以用前缀的英文混输方案感觉也比较符合

比如我输入zcl 就可以提示 close clock clone等 

这个需求要实现的话是需要在码表中增加前缀，还是通过lua解决呢？还是有其它更好的解决方案呢？

**Comment by bczhc** [comment]
首先那个反查用的pinyin_simp里没有“中华人民共和国”这个词，其次就算反查表里有，五笔表里没有，按反查逻辑也是不给出的，也不符合需求。单纯反查用的`reverse_lookup_translator`应该无法做到。

如果要拼音英文混输，一个想法是先建一个拼音+英文混输的方案，然后加个`affix_segmentor`，再给`recognizer`增加一个pattern，来指定以某某字符开始的输入，就临时进入那个拼音+英文混输的方案。

或者如果没有中英文混输的需求，把它们分开，比如设置以`|`开始就拼音输入，以`/`开始为英文输入，那直接增加俩`affix_segmentor`和`recognizer`就行了。

**Comment by plutotree** [comment]
> 首先那个反查用的pinyin_simp里没有“中华人民共和国”这个词，其次就算反查表里有，五笔表里没有，按反查逻辑也是不给出的，也不符合需求。单纯反查用的`reverse_lookup_translator`应该无法做到。
> 
> 如果要拼音英文混输，一个想法是先建一个拼音+英文混输的方案，然后加个`affix_segmentor`，再给`recognizer`增加一个pattern，来指定以某某字符开始的输入，就临时进入那个拼音+英文混输的方案。
> 
> 或者如果没有中英文混输的需求，把它们分开，比如设置以`|`开始就拼音输入，以`/`开始为英文输入，那直接增加俩`affix_segmentor`和`recognizer`就行了。

多谢了，我先学习下 `affix_segmentor` 相关配置。

另外贴下现在五笔的反查配置：
```yaml
reverse_lookup:
  dictionary: trident
  prefix: "z" 

recognizer:
  patterns:
    # z模式反查拼音
    reverse_lookup: "^z[a-z]*$"
```
纠正一点的是，反查的话没有要求五笔码表里面一定存在，如下图所示，除了前两个，后面的词在五笔码表里面都是不存在的

![image](https://github.com/user-attachments/assets/32b7f909-c430-4b99-901a-88e6ff97481d)

**Comment by plutotree** [comment]
我参考了[cangjie6.schema.yaml](https://github.com/LEOYoon-Tsaw/Cangjie6/blob/master/cangjie6.schema.yaml)的写法，基本上能比较好地满足我的需要。

核心配置如下，前缀z切换到拼音输入，前缀Z切换到英文输入，前缀X拼音反查。

```yaml
engine:
  segmentors:
    - affix_segmentor@pinyin
    - affix_segmentor@english
    - affix_segmentor@pinyin_lookup
  translators:
    - table_translator@english
    - script_translator@pinyin
    - script_translator@pinyin_lookup
  filters:
    - reverse_lookup_filter@pinyin_reverse_lookup
english:
  tag: english
  dictionary: melt_eng
  prefix: Z
  tips: [英语]
  comment_format: # 自定义提示码
    - xform/.*// # 清空提示码

pinyin:
  tag: pinyin
  dictionary: xxx_pinyin
  prefix: z
  tips: 【拼音】

pinyin_lookup:
  tag: pinyin_lookup
  prefix: "X"
  dictionary: xxx_pinyin
  tips: 【反查】

pinyin_reverse_lookup:
  tags:
    - pinyin_lookup
  dictionary: *dict
  overwrite_comment: true

recognizer:
  patterns:
    # X 实现拼音反查
    pinyin_lookup: "X[a-z]*$"

    # z开头输入拼音
    pinyin: "z[a-z']*$"

    # Z开关输入英文
    english: "Z[a-zA-Z]*$"
```

但是有遇到了下述问题：

1. 英文输入无法使用数字进行选词；


比如这种情况下，输入2
![image](https://github.com/user-attachments/assets/aafdafeb-3f84-4934-acdc-2643f31df973)
就会变成 `Zclo2`了（包含了我设置的前缀`Z`）
![image](https://github.com/user-attachments/assets/5ab90cba-3132-4f77-8e53-1f1cde5f133b)


2. 直接回车上屏包含前缀字符；

不管是英文还是拼音，如果我直接回车上屏的话，上屏的也是包含前缀字符`Z`，而这是我不希望的


辛苦帮忙看下，还需要进入哪里的修改~~ 感谢
