### ISSUE TITLE
vim下按Esc输入法状态切换问题

### ISSUE THREAD

**Issue by huo-feng-ding** [KyleBing/rime-wubi86-jidian#159]
不好意思，最近刚用上Rime，问题比较多，请见谅。

```  
 app_options:
    vim.exe:
      ascii_mode: true
      vim_mode: true
```

我配置了vim_mode后， 在vim软件里，进入插入模式时，使用中文输入法，此时打的字还未上屏，我想按 Esc 键进行清屏，操作的结果是清屏了，同时还将输入法切换成英文输入法。

正常想要的情况是这样的
1. 处于中文输入法状态时，此时未打字，直接按Esc键，输入法切换成英文状态，同时vim也切换成 NORMAL 模式。 （这个过程目前是没有问题）
2. 当中文输入法状态，打字还未上屏的情况下，按Esc键，只清屏，不切换成英文状态，vim也不切换成 NORMAL 模式。 （当前这个操作有问题）
