### ISSUE TITLE
关于自动造词的疑惑

### ISSUE THREAD

**Issue by f1ynng8** [KyleBing/rime-wubi86-jidian#16]
enable_encoder: true                  # 自动造词
  encode_commit_history: false          # 是否对已上屏的词自动造词

这两个选项，如果配置成如上状态时，想自动造词该如何使用？
之前看有人提到过需要delimiter？ 
具体是否还需要其它配置，以及实际造词时该如何操作？

**Comment by KyleBing** [comment]
因为之前没怎么用过这个功能，现在试了下，五笔模式下造词还需要其它一些设置

除了把文件中自动造词部分都设为 true 之后，还需要把 `speller` 那段的都注释掉，因为那里都是直接上屏的，直接上屏就无法造词了，所以需要注释掉。

造词功能是这样的，在输入一次之后，输入法会记住这个连词，打的时候后面会有图标指示，下次再输入这个词的时候，就会固定这个词，也就生成了这个词。

<img width="473" alt="Screen Shot 2019-11-17 at 21 40 11" src="https://user-images.githubusercontent.com/12215982/69008300-dd83f580-0983-11ea-9abe-a9dede7e7ee0.png">

<img width="469" alt="Screen Shot 2019-11-17 at 21 40 30" src="https://user-images.githubusercontent.com/12215982/69008303-e2e14000-0983-11ea-91ea-8a23fb3628f0.png">

<img width="489" alt="Screen Shot 2019-11-17 at 21 41 08" src="https://user-images.githubusercontent.com/12215982/69008307-e7a5f400-0983-11ea-9afa-fffbbdca3e7a.png">


```yaml

speller:
#  max_code_length: 4                    # 四码上屏
#  auto_select: true                     # 自动上屏
#  auto_select_unique_candidate: true    # 无重码自动上屏
translator:
  # 开启自动造词相关设置
  enable_sentence: false                # 是否开启自动造词
  enable_user_dict: false               # 是否开启用户词典（用户词典记录动态字词频，用户词）
  enable_encoder: false                 # 自动造词
  encode_commit_history: false          # 是否对已上屏的词自动造词
```
