### ISSUE TITLE
怎么设置中文状态下使用英文标点

### ISSUE THREAD

**Issue by gaoxinlei** [KyleBing/rime-wubi86-jidian#22]
辛苦作者，确实让我找回了极点五笔的感觉，打起来行云流水呢。
现在有两个问题，一个是并非纯五笔，目前是五笔拼音混输的情况，第二个就是没有办法便捷地设置中文状态下使用英文标点，而工作原因，我需要不时地切换这个，如果不能切换，能永远设置为英文标点也好。
另外怎么定义一些快捷键之类的呢，比如删词，甚至包含切换中英文标点的快捷键，特殊原因，目前是直接切换英文模式，再切回来继续打字。

**Comment by KyleBing** [comment]
## 设置默认英文标点输出

打开 `wubi86_jidian.schema.yaml` 这个文件，定位到 `switchs` 这个字段：

```yaml
switches:
  - name: full_shape
    states: [ 半角, 全角 ]
  - name: extended_charset
    states: [ 常用, 扩展 ]

# 添加下面的 reset 内容：注意要与上面的字段冲齐，空格多少要一致，不然出错
# 1: 默认英文标点 | 0: 默认中文标点
  - name: ascii_punct
    states: [ 。，, ．， ]
    reset: 1
```

## 对于词库的快捷键操作
目前没有，只能手动去词库添加或删除
