### ISSUE TITLE
请教一下键盘的显示在哪里增加？

### ISSUE THREAD

**Issue by youanan** [KyleBing/rime-wubi86-jidian#26]
想自定义一些键盘符号，不知道要修改哪个文件？
例如:我想把 r 字母上的$ 符号，改成￥呢？

**Comment by KyleBing** [comment]
在 `default.custom.yaml` 这个文件中修改即可

```yaml
  punctuator:
    full_shape:  #全角符号
    half_shape:  #半角符号 
```

标点在中文状态下是 <kbd>￥</kbd> 在英文状态下是  <kbd>$</kbd>
