### ISSUE TITLE
需要在小狼豪的配置添加style

### ISSUE THREAD

**Issue by chengyi** [KyleBing/rime-wubi86-jidian#35]
需要添加style以确保计算机重启后 输入法的外观不会变的难看，如我的配置
```yaml
patch:
  style:
    color_scheme: WhiteAqua
    display_tray_icon: false
    font_face: "Microsoft YaHei UI"
    horizontal: true    #横向排列候选
    font_point: 13      #字号13
    label_format: "%s"
    inline_preedit: true
    layout:
      min_width: 160
      min_height: 0
      border_width: 1
      margin_x: 12
      margin_y: 12
      spacing: 10
      candidate_spacing: 24
      hilite_spacing: 8
      hilite_padding: 12
      round_corner: 0
```
