### ISSUE TITLE
想问一下这种是哪个关键配置实现的？

### ISSUE THREAD

**Issue by xiebruce** [KyleBing/rime-wubi86-jidian#43]
如图，就是上边显示你输入的编码，默认都是没有的，我想要设置成这种，不知道是用哪个配置实现的？而且我是鼠须管不是Windows的小狼毫哦
![image](https://user-images.githubusercontent.com/13575500/85889792-b85f3b80-b81e-11ea-9f8f-e09214655ba7.png)

**Comment by KyleBing** [comment]
<img width="897" alt="Screen Shot 2020-06-27 at 10 07 58" src="https://user-images.githubusercontent.com/12215982/85912296-19f2ca80-b85e-11ea-9721-92584f78f930.png">

**Comment by xiebruce** [comment]
我后来发现，只需要添加`squirrel.custom.yaml`，并在其中填上以下配置，把style.inline_preedit设置为false就是双行显示(上边显示输入的按键，下边显示中文)
```yaml
patch:
  app_options:
    {}
  style:
    color_scheme: clean_white
    horizontal: true
    inline_preedit: false # true为单行显示，false为双行显示
    corner_radius: 5
```
