### ISSUE TITLE
z键重复输出

### ISSUE THREAD

**Issue by JJHZBKX** [KyleBing/rime-wubi86-jidian#46]
请问可以实现z键重复输出上一次的输出内容的功能吗？就像windows版的qq五笔一样

**Comment by fcying** [comment]
加上history就行
````
  translators:
    - history_translator@history
history:
  input: z
  size: 1
  initial_quality: 1000
```
