### ISSUE TITLE
请教如何移动候选码

### ISSUE THREAD

**Issue by grayguest** [KyleBing/rime-wubi86-jidian#48]
之前习惯了用+，想修改成+号作为候选码的移动，在配置文件和说明文档中木找到。。

**Comment by KyleBing** [comment]
在 `default.custom.yaml`  文件中

在  `key_binder` 的 `bindings` 下面添加如下内容，跟其它的对齐即可，前后无所谓。

```yaml
      # 上下翻页 - =
      - {accept: minus, send: Page_Up, when: paging}
      - {accept: equal, send: Page_Down, when: has_menu}
```

或者直接更新一下，我刚修改并提交了

**Comment by grayguest** [comment]
> 在 `default.custom.yaml` 文件中
> 
> 在 `key_binder` 的 `bindings` 下面添加如下内容，跟其它的对齐即可，前后无所谓。
> 
> ```yaml
>       # 上下翻页 - =
>       - {accept: minus, send: Page_Up, when: paging}
>       - {accept: equal, send: Page_Down, when: has_menu}
> ```
> 
> 或者直接更新一下，我刚修改并提交了 [添加 - = 上下翻页功能](https://github.com/KyleBing/rime-wubi86-jidian/commit/e366bbe3c6724f38146d039059ce0c868731999c)

多谢老师，已经更新了，非常顺手，我还想问一下，就是我造的词在哪个文件中呀，没找到。。。

**Comment by KyleBing** [comment]
通过什么造的词？

**Comment by grayguest** [comment]
> 通过什么造的词？

就是输入法打字的时候造的，把这些选项都enable了
```
speller:
  # max_code_length: 4                    # 四码上屏
  # auto_select: true                     # 自动上屏

translator:
  dictionary: wubi86_jidian             # 翻译器将调取此字典文件
  enable_charset_filter: true           # 开启字符集过滤
  enable_completion: true               # 是否显示编码未输入完整的词条
  enable_sentence: true                # 句子输入模式
  enable_user_dict: true               # 是否开启用户词典（用户词典记录动态字词频，用户词）
  enable_encoder: true
```

PS：老师济南的啊，哈哈，我济宁的。济宁这个词刚造完，问这个字怎么还有繁体的。。。你打打试试，第一个是问是简体，第二个问是繁体。
