### ISSUE TITLE
中文输入法下如何快速输入网址?

### ISSUE THREAD

**Issue by xtvj** [KyleBing/rime-wubi86-jidian#49]
之前用官方默认的输入法设置可以在不切换英文输入法下输入网址。“。”会自动变成“.”，而且不自动上屏。
发现你这个设置输入体验更好，就是习惯了输入网址时不切换输入法，我用的是wubi86_jidian_pinyin。
有方式修改么？要修改哪里呢？

**Comment by KyleBing** [comment]
凡是匹配 `^(www[.]|https?:|ftp[.:]|mailto:|file:|localhost).*$|^[a-z]+[.].+$` 里面内容的输入都不会自动上屏。
如 `www.` 开头的 `http` 开头的，可以根据自己需要修改 `default.custom.yaml` 文件最后的部分：

```yaml
  recognizer:
    patterns:
      email: "^[-_.0-9A-Za-z]*@.*$"
      uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
      url: "^(www[.]|https?:|ftp[.:]|mailto:|file:|localhost).*$|^[a-z]+[.].+$"
```
