### ISSUE TITLE
有谁了解 macOS 中的皮肤字段，欢迎补充

### ISSUE THREAD

**Issue by KyleBing** [KyleBing/rime-wubi86-jidian#5]
我想实现的皮肤效果如下，但目前如右

![skin_design](https://user-images.githubusercontent.com/12215982/60805393-89d1f600-a1b2-11e9-8801-cc1b87e208ac.png)

目前我了解的有这些，但是找不到设置首选背景颜色的字段。

```yaml
border_height: 5                          # 边距 - 面板上下
border_width: 5                           # 边距 - 面板左右
border_color: 0x8E8E93                    # 颜色 - 边框
back_color: 0xEFEFF4                      # 颜色 - 面板背景
label_color: 0x8E8E93                     # 颜色 - 候选序号
font_point: 18                            # 字体大小 - 候选
label_font_point: 18                      # 字体大小 - 候选序号
corner_radius: 5                          # 大小 - 圆角
horizontal: true                          # 是否横向 true 或 false
line_spacing: 10                          # horizental 为 false 时，上下候选的间隔大小
inline_preedit: true                      # 输入的编码是否直接写入编辑器中，如果为 false，未上屏的编码就会写在候选框中
spacing: 0                                # --- 未知
candidate_format: "%c %@ "                # 候选词格式，后面多个空格是为了增加候选词之间的距离
text_color: 0x000000                      # 颜色 - 输入中 - 文字
hilited_text_color: 0x8E8E93              # 颜色 - 输入中 - 编码
hilited_back_color: 0xEFEFF4              # 颜色 - 输入中 - 背景
hilited_candidate_text_color: 0xffffff    # 颜色 - 首选候选词 - 文字
hilited_candidate_back_color: 0x8E8E93    # 颜色 - 首选候选词 - 背景
hilited_candidate_label_color: 0xffffff   # 颜色 - 首选候选词 - 序号
candidate_text_color: 0x000000            # 颜色 - 其它候选词 - 文字
comment_text_color: 0x5AC461              # 颜色 - 其它候选词 - 提示编码
```
