### ISSUE TITLE
修改编码提示的显示方式

### ISSUE THREAD

**Issue by liebkne** [KyleBing/rime-wubi86-jidian#51]
<img width="108" alt="Screen Shot 2020-12-06 at 4 41 40 PM" src="https://user-images.githubusercontent.com/5475262/101275669-4c77fa80-37e2-11eb-9827-ddd0574a6cf8.png">

请问如何修改编码提示的显示方式？我想把波浪线删除，不知道是否可以……另外`qq`后面的那个上箭头是否也可以隐藏呢？谢谢。我不确定是否RIME本身的设置，如有打扰见谅。

**Comment by KyleBing** [comment]
修改 wubi86_jidian.schema.yaml 文件，在 `translator` 中添加如下内容。  `xform` 相当于 `replace` 替换功能，内容可以是正则表达式。
不显示提示码中的 `~` 只需要改成下面这样即可，意思是把 `~` 替换成空。

```yaml
translator:
  comment_format:                       # 提示码自定义
    - xform/~// 
```
