### ISSUE TITLE
怎樣支持五筆拼音混合輸入時，也能輸出繁體？

### ISSUE THREAD

**Issue by jettdavid23** [KyleBing/rime-wubi86-jidian#55]
我在設置繁體後，只能使用五筆輸入，不能使用五筆拼音混合輸入。

怎樣才能在五筆拼音混合輸入的同時，也能輸出繁體？

謝謝。

**Comment by KyleBing** [comment]
目前没有，你需要自己配置，把 `wubi86_jidian_trad.schema.yaml` 和 `wubi86_jidian_pinyin.schema.yaml` 的配置结合一下就好。

**Comment by jettdavid23** [comment]
@KyleBing 

謝謝回復，目前已照抄`wubi86_jidian_trad.schema.yaml`文件解決，順便把方法貼出來:

1. 編輯 `wubi86_jidian_pinyin.schema.yaml` 文件
2. 將 `switches`內的`ascii_mode`下面（同級）加入:

```yml
  - name: zh_trad
    reset: 1    # 初始状态为 0: 简 -> 繁 1: 繁 -> 简
    states: [ 简体, 繁体 ]
```

3. 在`engine`節點內加入:

```yml
  filters:
    - simplifier
    - uniquifier
 ```

4. 在 `reverse_lookup`後面（同一級）加入:

```yml
simplifier:    # 简入繁出，如果出不来，可能需要安装 opencc 简繁字转换库，github地址：https://github.com/BYVoid/OpenCC
  opencc_config: s2t.json
  # opencc_config: t2s.json   # 繁 -> 简【默认】
  # opencc_config: t2tw.json  # 繁 -> 台湾
  # opencc_config: t2hk.json  # 繁 -> 香港

  option_name: zh_trad
```

重新 `Deploy`，然後使用`Ctrl + 0`切換開關使用即可。
