### ISSUE TITLE
四字唯一自动上屏为什么没有生效？

### ISSUE THREAD

**Issue by falconchen** [KyleBing/rime-wubi86-jidian#90]
不知道我理解的“四字唯一自动上屏” 是不是不对？我想象中的这种情况下“唯一”两个字，因为是唯一的候选词，应该会自动上到搜索框，而不需要再按一次空格才上去，如果我理解错了还望多多包涵。
![demo](https://txhk.cellmean.com/photo/i/2023/02/20/hf8xkk-0.png)

这是我的 `wubi86_jidian.schema.yaml` 文件的部分相关配置，是不是哪里配置有问题？如果有需要我可以提供更多其他信息。

``` yaml
speller:
  max_code_length: 4                    # 四码上屏
  auto_select: true                     # 四码唯一时，自动上屏
  auto_select_unique_candidate: true                     #无重码自动上屏

translator:
  dictionary: wubi86_jidian             # 翻译器将调取此字典文件
  enable_charset_filter: true           # 开启字符集过滤
  enable_completion: true               # 是否显示编码未输入完整的词条
  enable_sentence: false                # 句子输入模式
  enable_user_dict: false               # 是否开启用户词典（用户词典记录动态字词频，用户词）
  enable_encoder: false
```
