### ISSUE TITLE
请问一下五笔下怎么默认半角呢？

### ISSUE THREAD

**Issue by vosho** [KyleBing/rime-wubi86-jidian#96]
谢谢

**Comment by KyleBing** [comment]
需要修改配置文件 `wubi86_jidian.schema.yaml` 里面，将 半角全角下面添加 `reset:0` 像下面这样就可以了。

```yaml
switches:
#  - name: ascii_mode
#    reset: 0
#    states: [ 中文, 英文 ]
  - name: zh_trad
    reset: 0    # 初始状态为 0: 简 -> 简 1: 简 -> 繁
    states: [ 简体, 繁体 ]
  - name: full_shape
    states: [ 半角, 全角 ]
    reset: 0
  - name: extended_charset
    states: [ 常用, 扩展 ]
  - name: ascii_punct
    states: [ 。，, ．， ]
```
